### ISSUE TITLE
온보딩 페이지

### ISSUE THREAD

**Issue by terry-koo** [Za-DO/Semo#99]

**Comment by Eunbi-Cho** [comment]
런치스크린 깨지는 거 1배율, 2배율, 3배율 크기의 이미지 사이즈 모두 넣어주니까 저는 해결되었었어요~

**Comment by terry-koo** [comment]
> 런치스크린 깨지는 거 1배율, 2배율, 3배율 크기의 이미지 사이즈 모두 넣어주니까 저는 해결되었었어요~

최고에요👍
